workflows:
    android-workflow:
        name: Android Workflow
        max_build_duration: 120
        instance_type: mac_mini_m2
        environment:
          android_signing:
            - keystore_reference