workflows:
    android-workflow:
        name: Android Workflow
        max_build_duration: 120
        instance_type: mac_mini_m2
        environment:
          android_signing:
            - React meandering-keystore
          vars:
            PACKAGE_NAME: "net.coventry.sleepless"
        scripts:
          - name: Install npm dependencies
            script: | 
              npm install
          - name: Set Android SDK location
            script: | 
              echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
          - name: Build Android release
            script: | 
              cd android
              ./gradlew bundleRelease

        artifacts:
          - android/app/build/outputs/**/*.aab

    ios-workflow:
        name: iOS Workflow
        max_build_duration: 120
        instance_type: mac_mini_m2
        environment:
          vars:
            BUNDLE_ID: "net.coventry.sleepless"
            XCODE_WORKSPACE: "meanderingsleep.xcworkspace"
            XCODE_SCHEME: "meanderingsleep"